// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: StatisticsEvent.proto
// Protobuf Java Version: 4.28.2

package org.shared;

public final class StatisticsEventOuterClass {
  private StatisticsEventOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      StatisticsEventOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.shared.DeliveryOption}
   */
  public enum DeliveryOption
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PICK_UP = 0;</code>
     */
    PICK_UP(0),
    /**
     * <code>DELIVERY = 1;</code>
     */
    DELIVERY(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        DeliveryOption.class.getName());
    }
    /**
     * <code>PICK_UP = 0;</code>
     */
    public static final int PICK_UP_VALUE = 0;
    /**
     * <code>DELIVERY = 1;</code>
     */
    public static final int DELIVERY_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DeliveryOption valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DeliveryOption forNumber(int value) {
      switch (value) {
        case 0: return PICK_UP;
        case 1: return DELIVERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeliveryOption>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DeliveryOption> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeliveryOption>() {
            public DeliveryOption findValueByNumber(int number) {
              return DeliveryOption.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.shared.StatisticsEventOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final DeliveryOption[] VALUES = values();

    public static DeliveryOption valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DeliveryOption(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.shared.DeliveryOption)
  }

  public interface StatisticsEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.shared.StatisticsEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 restaurantId = 1;</code>
     * @return The restaurantId.
     */
    long getRestaurantId();

    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     * @return Whether the orderDate field is set.
     */
    boolean hasOrderDate();
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     * @return The orderDate.
     */
    com.google.protobuf.Timestamp getOrderDate();
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder();

    /**
     * <code>double totalPrice = 3;</code>
     * @return The totalPrice.
     */
    double getTotalPrice();

    /**
     * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
     * @return The enum numeric value on the wire for deliveryOption.
     */
    int getDeliveryOptionValue();
    /**
     * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
     * @return The deliveryOption.
     */
    org.shared.StatisticsEventOuterClass.DeliveryOption getDeliveryOption();
  }
  /**
   * Protobuf type {@code org.shared.StatisticsEvent}
   */
  public static final class StatisticsEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.shared.StatisticsEvent)
      StatisticsEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        StatisticsEvent.class.getName());
    }
    // Use StatisticsEvent.newBuilder() to construct.
    private StatisticsEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StatisticsEvent() {
      deliveryOption_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shared.StatisticsEventOuterClass.internal_static_org_shared_StatisticsEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shared.StatisticsEventOuterClass.internal_static_org_shared_StatisticsEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shared.StatisticsEventOuterClass.StatisticsEvent.class, org.shared.StatisticsEventOuterClass.StatisticsEvent.Builder.class);
    }

    private int bitField0_;
    public static final int RESTAURANTID_FIELD_NUMBER = 1;
    private long restaurantId_ = 0L;
    /**
     * <code>int64 restaurantId = 1;</code>
     * @return The restaurantId.
     */
    @java.lang.Override
    public long getRestaurantId() {
      return restaurantId_;
    }

    public static final int ORDERDATE_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp orderDate_;
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     * @return Whether the orderDate field is set.
     */
    @java.lang.Override
    public boolean hasOrderDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     * @return The orderDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getOrderDate() {
      return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder() {
      return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
    }

    public static final int TOTALPRICE_FIELD_NUMBER = 3;
    private double totalPrice_ = 0D;
    /**
     * <code>double totalPrice = 3;</code>
     * @return The totalPrice.
     */
    @java.lang.Override
    public double getTotalPrice() {
      return totalPrice_;
    }

    public static final int DELIVERYOPTION_FIELD_NUMBER = 4;
    private int deliveryOption_ = 0;
    /**
     * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
     * @return The enum numeric value on the wire for deliveryOption.
     */
    @java.lang.Override public int getDeliveryOptionValue() {
      return deliveryOption_;
    }
    /**
     * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
     * @return The deliveryOption.
     */
    @java.lang.Override public org.shared.StatisticsEventOuterClass.DeliveryOption getDeliveryOption() {
      org.shared.StatisticsEventOuterClass.DeliveryOption result = org.shared.StatisticsEventOuterClass.DeliveryOption.forNumber(deliveryOption_);
      return result == null ? org.shared.StatisticsEventOuterClass.DeliveryOption.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (restaurantId_ != 0L) {
        output.writeInt64(1, restaurantId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getOrderDate());
      }
      if (java.lang.Double.doubleToRawLongBits(totalPrice_) != 0) {
        output.writeDouble(3, totalPrice_);
      }
      if (deliveryOption_ != org.shared.StatisticsEventOuterClass.DeliveryOption.PICK_UP.getNumber()) {
        output.writeEnum(4, deliveryOption_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (restaurantId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, restaurantId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOrderDate());
      }
      if (java.lang.Double.doubleToRawLongBits(totalPrice_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, totalPrice_);
      }
      if (deliveryOption_ != org.shared.StatisticsEventOuterClass.DeliveryOption.PICK_UP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, deliveryOption_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.shared.StatisticsEventOuterClass.StatisticsEvent)) {
        return super.equals(obj);
      }
      org.shared.StatisticsEventOuterClass.StatisticsEvent other = (org.shared.StatisticsEventOuterClass.StatisticsEvent) obj;

      if (getRestaurantId()
          != other.getRestaurantId()) return false;
      if (hasOrderDate() != other.hasOrderDate()) return false;
      if (hasOrderDate()) {
        if (!getOrderDate()
            .equals(other.getOrderDate())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getTotalPrice())
          != java.lang.Double.doubleToLongBits(
              other.getTotalPrice())) return false;
      if (deliveryOption_ != other.deliveryOption_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESTAURANTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRestaurantId());
      if (hasOrderDate()) {
        hash = (37 * hash) + ORDERDATE_FIELD_NUMBER;
        hash = (53 * hash) + getOrderDate().hashCode();
      }
      hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalPrice()));
      hash = (37 * hash) + DELIVERYOPTION_FIELD_NUMBER;
      hash = (53 * hash) + deliveryOption_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.shared.StatisticsEventOuterClass.StatisticsEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.shared.StatisticsEventOuterClass.StatisticsEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.shared.StatisticsEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.shared.StatisticsEvent)
        org.shared.StatisticsEventOuterClass.StatisticsEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shared.StatisticsEventOuterClass.internal_static_org_shared_StatisticsEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shared.StatisticsEventOuterClass.internal_static_org_shared_StatisticsEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shared.StatisticsEventOuterClass.StatisticsEvent.class, org.shared.StatisticsEventOuterClass.StatisticsEvent.Builder.class);
      }

      // Construct using org.shared.StatisticsEventOuterClass.StatisticsEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getOrderDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        restaurantId_ = 0L;
        orderDate_ = null;
        if (orderDateBuilder_ != null) {
          orderDateBuilder_.dispose();
          orderDateBuilder_ = null;
        }
        totalPrice_ = 0D;
        deliveryOption_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shared.StatisticsEventOuterClass.internal_static_org_shared_StatisticsEvent_descriptor;
      }

      @java.lang.Override
      public org.shared.StatisticsEventOuterClass.StatisticsEvent getDefaultInstanceForType() {
        return org.shared.StatisticsEventOuterClass.StatisticsEvent.getDefaultInstance();
      }

      @java.lang.Override
      public org.shared.StatisticsEventOuterClass.StatisticsEvent build() {
        org.shared.StatisticsEventOuterClass.StatisticsEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.shared.StatisticsEventOuterClass.StatisticsEvent buildPartial() {
        org.shared.StatisticsEventOuterClass.StatisticsEvent result = new org.shared.StatisticsEventOuterClass.StatisticsEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.shared.StatisticsEventOuterClass.StatisticsEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.restaurantId_ = restaurantId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.orderDate_ = orderDateBuilder_ == null
              ? orderDate_
              : orderDateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalPrice_ = totalPrice_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.deliveryOption_ = deliveryOption_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shared.StatisticsEventOuterClass.StatisticsEvent) {
          return mergeFrom((org.shared.StatisticsEventOuterClass.StatisticsEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shared.StatisticsEventOuterClass.StatisticsEvent other) {
        if (other == org.shared.StatisticsEventOuterClass.StatisticsEvent.getDefaultInstance()) return this;
        if (other.getRestaurantId() != 0L) {
          setRestaurantId(other.getRestaurantId());
        }
        if (other.hasOrderDate()) {
          mergeOrderDate(other.getOrderDate());
        }
        if (other.getTotalPrice() != 0D) {
          setTotalPrice(other.getTotalPrice());
        }
        if (other.deliveryOption_ != 0) {
          setDeliveryOptionValue(other.getDeliveryOptionValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                restaurantId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getOrderDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                totalPrice_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 32: {
                deliveryOption_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long restaurantId_ ;
      /**
       * <code>int64 restaurantId = 1;</code>
       * @return The restaurantId.
       */
      @java.lang.Override
      public long getRestaurantId() {
        return restaurantId_;
      }
      /**
       * <code>int64 restaurantId = 1;</code>
       * @param value The restaurantId to set.
       * @return This builder for chaining.
       */
      public Builder setRestaurantId(long value) {

        restaurantId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 restaurantId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRestaurantId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        restaurantId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp orderDate_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> orderDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       * @return Whether the orderDate field is set.
       */
      public boolean hasOrderDate() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       * @return The orderDate.
       */
      public com.google.protobuf.Timestamp getOrderDate() {
        if (orderDateBuilder_ == null) {
          return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
        } else {
          return orderDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder setOrderDate(com.google.protobuf.Timestamp value) {
        if (orderDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderDate_ = value;
        } else {
          orderDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder setOrderDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (orderDateBuilder_ == null) {
          orderDate_ = builderForValue.build();
        } else {
          orderDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder mergeOrderDate(com.google.protobuf.Timestamp value) {
        if (orderDateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            orderDate_ != null &&
            orderDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getOrderDateBuilder().mergeFrom(value);
          } else {
            orderDate_ = value;
          }
        } else {
          orderDateBuilder_.mergeFrom(value);
        }
        if (orderDate_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder clearOrderDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        orderDate_ = null;
        if (orderDateBuilder_ != null) {
          orderDateBuilder_.dispose();
          orderDateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getOrderDateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getOrderDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder() {
        if (orderDateBuilder_ != null) {
          return orderDateBuilder_.getMessageOrBuilder();
        } else {
          return orderDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getOrderDateFieldBuilder() {
        if (orderDateBuilder_ == null) {
          orderDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getOrderDate(),
                  getParentForChildren(),
                  isClean());
          orderDate_ = null;
        }
        return orderDateBuilder_;
      }

      private double totalPrice_ ;
      /**
       * <code>double totalPrice = 3;</code>
       * @return The totalPrice.
       */
      @java.lang.Override
      public double getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>double totalPrice = 3;</code>
       * @param value The totalPrice to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPrice(double value) {

        totalPrice_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double totalPrice = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPrice_ = 0D;
        onChanged();
        return this;
      }

      private int deliveryOption_ = 0;
      /**
       * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
       * @return The enum numeric value on the wire for deliveryOption.
       */
      @java.lang.Override public int getDeliveryOptionValue() {
        return deliveryOption_;
      }
      /**
       * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
       * @param value The enum numeric value on the wire for deliveryOption to set.
       * @return This builder for chaining.
       */
      public Builder setDeliveryOptionValue(int value) {
        deliveryOption_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
       * @return The deliveryOption.
       */
      @java.lang.Override
      public org.shared.StatisticsEventOuterClass.DeliveryOption getDeliveryOption() {
        org.shared.StatisticsEventOuterClass.DeliveryOption result = org.shared.StatisticsEventOuterClass.DeliveryOption.forNumber(deliveryOption_);
        return result == null ? org.shared.StatisticsEventOuterClass.DeliveryOption.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
       * @param value The deliveryOption to set.
       * @return This builder for chaining.
       */
      public Builder setDeliveryOption(org.shared.StatisticsEventOuterClass.DeliveryOption value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        deliveryOption_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.shared.DeliveryOption deliveryOption = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeliveryOption() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deliveryOption_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.shared.StatisticsEvent)
    }

    // @@protoc_insertion_point(class_scope:org.shared.StatisticsEvent)
    private static final org.shared.StatisticsEventOuterClass.StatisticsEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.shared.StatisticsEventOuterClass.StatisticsEvent();
    }

    public static org.shared.StatisticsEventOuterClass.StatisticsEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatisticsEvent>
        PARSER = new com.google.protobuf.AbstractParser<StatisticsEvent>() {
      @java.lang.Override
      public StatisticsEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StatisticsEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatisticsEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.shared.StatisticsEventOuterClass.StatisticsEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_shared_StatisticsEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_shared_StatisticsEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025StatisticsEvent.proto\022\norg.shared\032\037goo" +
      "gle/protobuf/timestamp.proto\"\236\001\n\017Statist" +
      "icsEvent\022\024\n\014restaurantId\030\001 \001(\003\022-\n\torderD" +
      "ate\030\002 \001(\0132\032.google.protobuf.Timestamp\022\022\n" +
      "\ntotalPrice\030\003 \001(\001\0222\n\016deliveryOption\030\004 \001(" +
      "\0162\032.org.shared.DeliveryOption*+\n\016Deliver" +
      "yOption\022\013\n\007PICK_UP\020\000\022\014\n\010DELIVERY\020\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_org_shared_StatisticsEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_shared_StatisticsEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_shared_StatisticsEvent_descriptor,
        new java.lang.String[] { "RestaurantId", "OrderDate", "TotalPrice", "DeliveryOption", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
